/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  introSidebar: [{type: 'autogenerated', dirName: 'intro'}],
  docsSidebar: [{type: 'autogenerated', dirName: 'docs'}]
};

export default sidebars;
