/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  docsSidebar: [{type: 'autogenerated', dirName: 'docs'}]
};

export default sidebars;
