/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  introSidebar: [{type: 'doc', id: 'intro'}, {type: 'autogenerated', dirName: 'intro'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  docsSidebar: [{type: 'autogenerated', dirName: 'documentation'}]
};

export default sidebars;
